/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SquadsRouteImport } from './routes/squads'
import { Route as SeasonPassRouteImport } from './routes/season-pass'
import { Route as MatchupRouteImport } from './routes/matchup'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FantasyRouteImport } from './routes/fantasy'
import { Route as IndexRouteImport } from './routes/index'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsRoute = SquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonPassRoute = SeasonPassRouteImport.update({
  id: '/season-pass',
  path: '/season-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupRoute = MatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyRoute = FantasyRouteImport.update({
  id: '/fantasy',
  path: '/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fantasy': typeof FantasyRoute
  '/guide': typeof GuideRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/matchup': typeof MatchupRoute
  '/season-pass': typeof SeasonPassRoute
  '/squads': typeof SquadsRoute
  '/story': typeof StoryRoute
  '/terminal': typeof TerminalRoute
  '/venues': typeof VenuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fantasy': typeof FantasyRoute
  '/guide': typeof GuideRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/matchup': typeof MatchupRoute
  '/season-pass': typeof SeasonPassRoute
  '/squads': typeof SquadsRoute
  '/story': typeof StoryRoute
  '/terminal': typeof TerminalRoute
  '/venues': typeof VenuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fantasy': typeof FantasyRoute
  '/guide': typeof GuideRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/matchup': typeof MatchupRoute
  '/season-pass': typeof SeasonPassRoute
  '/squads': typeof SquadsRoute
  '/story': typeof StoryRoute
  '/terminal': typeof TerminalRoute
  '/venues': typeof VenuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fantasy'
    | '/guide'
    | '/match/$matchId'
    | '/live'
    | '/login'
    | '/matches'
    | '/matchup'
    | '/season-pass'
    | '/squads'
    | '/story'
    | '/terminal'
    | '/venues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fantasy'
    | '/guide'
    | '/match/$matchId'
    | '/live'
    | '/login'
    | '/matches'
    | '/matchup'
    | '/season-pass'
    | '/squads'
    | '/story'
    | '/terminal'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/fantasy'
    | '/guide'
    | '/match/$matchId'
    | '/live'
    | '/login'
    | '/matches'
    | '/matchup'
    | '/season-pass'
    | '/squads'
    | '/story'
    | '/terminal'
    | '/venues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FantasyRoute: typeof FantasyRoute
  GuideRoute: typeof GuideRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  MatchupRoute: typeof MatchupRoute
  SeasonPassRoute: typeof SeasonPassRoute
  SquadsRoute: typeof SquadsRoute
  StoryRoute: typeof StoryRoute
  TerminalRoute: typeof TerminalRoute
  VenuesRoute: typeof VenuesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads': {
      id: '/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof SquadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-pass': {
      id: '/season-pass'
      path: '/season-pass'
      fullPath: '/season-pass'
      preLoaderRoute: typeof SeasonPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup': {
      id: '/matchup'
      path: '/matchup'
      fullPath: '/matchup'
      preLoaderRoute: typeof MatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy': {
      id: '/fantasy'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FantasyRoute: FantasyRoute,
  GuideRoute: GuideRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  MatchupRoute: MatchupRoute,
  SeasonPassRoute: SeasonPassRoute,
  SquadsRoute: SquadsRoute,
  StoryRoute: StoryRoute,
  TerminalRoute: TerminalRoute,
  VenuesRoute: VenuesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
